version: '1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASSWORD: sa
    ports:
      - "3306:3306"