server:
  port : 8081

spring:
  devtools:
    livereload:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    cache: false # 개발 시에는 캐시를 끄는 것이 좋습니다.
#    prefix: classpath:/templates/
    suffix: .html

  profiles:
    include: jwt #jwt.yml
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
      open-in-view: ture

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mechuli-db.cyzrnn6eoqnk.ap-northeast-2.rds.amazonaws.com:3306/mechuli?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: master
    password: mechuliproject


jwt:
  secret: 63fba97a41e0d004e10e8dbbcb9a547819280efb00a54c732aca36a8a58258e4fcc539ffc5159a7f0a7be78b86efe001c12ba6af6debeb0a89e8ce7e82e75455

  access:
    expiration: 8000
    header: Authorization

  refresh:
    expiration: 9000
    header: Authorization-refresh



springdoc:
  swagger-ui:
    path: swagger            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # delete - get - patch - post - put 순으로 정렬됨
    api-docs:
      path: /api-docs/json
      groups:
        enabled: true
    cache:
      disabled: true
logging:
      level:
        org.hibernate.SQL: debug

sql:
    init:
      mode: always