ALTER TABLE tb_user
    ADD address VARCHAR(255);

ALTER TABLE tb_user
    ADD create_date TIMESTAMP;

ALTER TABLE tb_user
    ADD idx BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL;

ALTER TABLE tb_user
    ADD update_date TIMESTAMP;

ALTER TABLE tb_user
    ADD user_id VARCHAR(255);

ALTER TABLE tb_user
    ADD user_pw VARCHAR(255);

ALTER TABLE tb_user
    ADD CONSTRAINT pk_tb_user PRIMARY KEY (idx);