
ALTER TABLE tb_user
    ADD created_at TIMESTAMP;

ALTER TABLE tb_user
    ADD idx BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL;

ALTER TABLE tb_user
    ADD oath VARCHAR(255);

ALTER TABLE tb_user
    ADD role_type VARCHAR(255);

ALTER TABLE tb_user
    ADD update_at TIMESTAMP;

ALTER TABLE tb_user
    ADD user_id VARCHAR(255);

ALTER TABLE tb_user
    ADD user_pw VARCHAR(255);

ALTER TABLE tb_user
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE tb_user
    ALTER COLUMN user_pw SET NOT NULL;

ALTER TABLE tb_user
    ADD CONSTRAINT pk_tb_user PRIMARY KEY (idx);